-- 003_partitions.sql
--
-- INTENTIONALLY EMPTY. This migration performs no DDL.
--
-- It originally created 15 hardcoded daily partitions covering
-- 2026-08-09 through 2026-08-23, as a deterministic bootstrap so the
-- service had somewhere to write immediately after the first
-- `docker compose up`. That bootstrap is now redundant and was removed.
--
-- Why it was removed
--
--   1. It is superseded. src/db/retention.ts runs a full provisioning
--      pass during startup -- awaited, and fatal on failure, BEFORE
--      /health can report ready. It creates every daily partition from
--      RETENTION_DAYS in the past through PARTITION_LOOKAHEAD_DAYS in
--      the future, which is a strict superset of what this file used
--      to create. Proven live: dropping a partition by hand and
--      restarting the app recreated it automatically
--      ("Partition maintenance: +1 provisioned").
--
--   2. Its dates expired. Hardcoded bounds are deterministic, which is
--      the property a migration must have -- but they are only USEFUL
--      while the deployment date sits inside them. Deployed after
--      2026-08-23, this file created 15 partitions in the past that the
--      retention job then dropped within seconds of the same startup.
--
--   3. It masked a real defect. The incidental coverage of a couple of
--      past days hid the fact that nothing provisioned the past at all.
--      A log arriving late -- a buffered agent, a replayed dead-letter
--      batch, a skewed clock -- passes validation (§8 bounds only the
--      future) but had no partition to land in, so the COPY failed and
--      returned 500, taking every valid entry in the same batch with
--      it. Fixed by provisioning backwards across the retention window
--      and rejecting anything older per-entry.
--
-- Why the file still exists rather than being deleted
--
--   Deleting it would leave a gap at 003 in a sequence the runner
--   tracks by filename in schema_migrations. A future migration
--   accidentally numbered 003 would then be skipped as "already
--   applied" on any database that ran the original. Keeping an inert
--   file makes that impossible and leaves the reasoning where the next
--   reader will look for it.
--
-- Partition creation now lives entirely in the application layer; see
-- src/db/retention.ts and the retention section of README.md.
